version: '3.8'
services:
    nginx:
        container_name: nginx
        build:
            context: ./.docker/nginx
        volumes:
            - ./:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - ${NGINX_PORT:-8092}:80
        depends_on:
            - oneportal
        env_file:
            - .env.nginx
        networks:
            - mon_app_net
        # environment:
        #     - NGINX_HOST=${NGINX_HOST}
        #     - NGINX_PORT=${NGINX_PORT:-8092}
    database:
        container_name: database
        image: mariadb:10.11.4
        volumes:
            - ./docker/mariadb:/var/lib/mariadb        
        restart: always
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        ports:
            - ${MARIADB_PORT:-3306}:3306
        networks:
            - mon_app_net
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:22.0.1
        restart: always
        environment:
           KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
           KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
        ports:
            - ${KEYCLOACK_PORT:-8090}:8080
        networks:
            - mon_app_net
        command: start-dev
    # oneportal:
    #     container_name: one_portal
    #     build:
    #         context: ./
    #         dockerfile: Dockerfile
    #     image: app_one_portal
    #     depends_on:
    #         - db
    #     ports:
    #       - ${APP_PORT:-3000}:3000
    #     networks:
    #         - mon_app_net
    oneportal:
        container_name: oneportal
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        depends_on:
            - database
            
        volumes:
            - ./:/var/www/symfony:cached
            - symfony_app_var:/var/www/symfony/var
            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
          - ${APP_PORT:-3000}:3000
        networks:
            - mon_app_net
volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:
networks:
    mon_app_net:
     driver: bridge