controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# app_list:
#     path: /Deconnection
#     methods:   GET
app_register:
    path: /admin/register
    methods:   POST
app_liste:
    path: /liste
    methods:   GET
app_edit:
  path: '/edit/{id}'
  controller: App\Controller\AdminController::edit
  methods: GET
app_logout:
    path: /logout
    methods: GET
app_delete:
    path: /delete/{id}
    controller: App\Controller\AdminController::delete
    methods: GET
app_role:
    path: /getRole
    controller: App\Controller\SecurityController::role
    methods: GET
# app_card:
#     path: /Application/{id}
#     controller: App\Controller\UseController::listeCard
#     methods: GET